import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import '@fontsource/roboto/300.css';
import ClientLayout from "./ui/root-layout";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
});


export const metadata: Metadata = {
  title: "Cuidarte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
